// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	errs "github.com/danisbagus/go-common-packages/errs"
	dto "github.com/danisbagus/matchoshop/internal/dto"

	mock "github.com/stretchr/testify/mock"
)

// IProductCategoryService is an autogenerated mock type for the IProductCategoryService type
type IProductCategoryService struct {
	mock.Mock
}

// Create provides a mock function with given fields: data
func (_m *IProductCategoryService) Create(data *dto.CreateProductCategoryRequest) (*dto.ResponseData, *errs.AppError) {
	ret := _m.Called(data)

	var r0 *dto.ResponseData
	if rf, ok := ret.Get(0).(func(*dto.CreateProductCategoryRequest) *dto.ResponseData); ok {
		r0 = rf(data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.ResponseData)
		}
	}

	var r1 *errs.AppError
	if rf, ok := ret.Get(1).(func(*dto.CreateProductCategoryRequest) *errs.AppError); ok {
		r1 = rf(data)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*errs.AppError)
		}
	}

	return r0, r1
}

// Delete provides a mock function with given fields: productCategoryID
func (_m *IProductCategoryService) Delete(productCategoryID int64) (*dto.ResponseData, *errs.AppError) {
	ret := _m.Called(productCategoryID)

	var r0 *dto.ResponseData
	if rf, ok := ret.Get(0).(func(int64) *dto.ResponseData); ok {
		r0 = rf(productCategoryID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.ResponseData)
		}
	}

	var r1 *errs.AppError
	if rf, ok := ret.Get(1).(func(int64) *errs.AppError); ok {
		r1 = rf(productCategoryID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*errs.AppError)
		}
	}

	return r0, r1
}

// GetDetail provides a mock function with given fields: productCategoryID
func (_m *IProductCategoryService) GetDetail(productCategoryID int64) (*dto.ResponseData, *errs.AppError) {
	ret := _m.Called(productCategoryID)

	var r0 *dto.ResponseData
	if rf, ok := ret.Get(0).(func(int64) *dto.ResponseData); ok {
		r0 = rf(productCategoryID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.ResponseData)
		}
	}

	var r1 *errs.AppError
	if rf, ok := ret.Get(1).(func(int64) *errs.AppError); ok {
		r1 = rf(productCategoryID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*errs.AppError)
		}
	}

	return r0, r1
}

// GetList provides a mock function with given fields:
func (_m *IProductCategoryService) GetList() (*dto.ResponseData, *errs.AppError) {
	ret := _m.Called()

	var r0 *dto.ResponseData
	if rf, ok := ret.Get(0).(func() *dto.ResponseData); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.ResponseData)
		}
	}

	var r1 *errs.AppError
	if rf, ok := ret.Get(1).(func() *errs.AppError); ok {
		r1 = rf()
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*errs.AppError)
		}
	}

	return r0, r1
}

// Update provides a mock function with given fields: productCategoryID, data
func (_m *IProductCategoryService) Update(productCategoryID int64, data *dto.CreateProductCategoryRequest) (*dto.ResponseData, *errs.AppError) {
	ret := _m.Called(productCategoryID, data)

	var r0 *dto.ResponseData
	if rf, ok := ret.Get(0).(func(int64, *dto.CreateProductCategoryRequest) *dto.ResponseData); ok {
		r0 = rf(productCategoryID, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.ResponseData)
		}
	}

	var r1 *errs.AppError
	if rf, ok := ret.Get(1).(func(int64, *dto.CreateProductCategoryRequest) *errs.AppError); ok {
		r1 = rf(productCategoryID, data)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*errs.AppError)
		}
	}

	return r0, r1
}
