version: '3'
services:
  db:
    image: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - db-matchoshop:/var/lib/postgresql/data
      - ./db/initdb/init.sql:/docker-entrypoint-initdb.d/init.sql
    container_name: matchoshop-db
    environment:
      POSTGRES_PASSWORD: mypass
      POSTGRES_USER: user123
      POSTGRES_DB: matchoshop

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8011:8080
    container_name: matchoshop-adminer

  sonarqube:
    image: sonarqube
    container_name: matchoshop-sonarqube
    restart: unless-stopped
    environment:
    - SONARQUBE_JDBC_USERNAME=user123
    - SONARQUBE_JDBC_PASSWORD=mypass
    - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/matchoshop
    ports:
    - "9000:9000"
    - "9092:9092"
    volumes:
    - sonarqube_conf:/opt/sonarqube/conf
    - sonarqube_data:/opt/sonarqube/data
    - sonarqube_extensions:/opt/sonarqube/extensions
    - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins

volumes:
  db-matchoshop:
    driver: local
  sonarqube_bundled-plugins:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions: