// Code generated by mockery v2.30.16. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IHealthcheckRepository is an autogenerated mock type for the IHealthcheckRepository type
type IHealthcheckRepository struct {
	mock.Mock
}

// Get provides a mock function with given fields:
func (_m *IHealthcheckRepository) Get() map[string]interface{} {
	ret := _m.Called()

	var r0 map[string]interface{}
	if rf, ok := ret.Get(0).(func() map[string]interface{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	return r0
}

// NewIHealthcheckRepository creates a new instance of IHealthcheckRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIHealthcheckRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *IHealthcheckRepository {
	mock := &IHealthcheckRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
